# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{active_cart}
  s.version = "0.0.18"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Myles Eftos"]
  s.date = %q{2010-10-07}
  s.description = %q{You can use active_cart as the basis of a shopping cart system. It's not a shopping cart application - it's a shopping cart framework.}
  s.email = %q{myles@madpilot.com.au}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "active_cart.gemspec",
     "install.rb",
     "lib/active_cart.rb",
     "lib/active_cart/acts_as_cart.rb",
     "lib/active_cart/cart.rb",
     "lib/active_cart/cart_storage.rb",
     "lib/active_cart/item.rb",
     "lib/active_cart/items/memory_item.rb",
     "lib/active_cart/order_total.rb",
     "lib/active_cart/order_total_collection.rb",
     "lib/active_cart/storage_engines/memory.rb",
     "lib/exceptions/out_of_stock.rb",
     "test/blueprints.rb",
     "test/fixtures/cart.rb",
     "test/fixtures/cart_item.rb",
     "test/fixtures/item.rb",
     "test/fixtures/order_total.rb",
     "test/mocks/test_cart_storage.rb",
     "test/mocks/test_item.rb",
     "test/mocks/test_order_total.rb",
     "test/performance/browsing_test.rb",
     "test/schema.rb",
     "test/test_helper.rb",
     "test/unit/acts_as_cart_test.rb",
     "test/unit/cart_storage_test.rb",
     "test/unit/cart_test.rb",
     "test/unit/item_test.rb",
     "test/unit/order_total_collection_test.rb",
     "uninstall.rb"
  ]
  s.homepage = %q{http://gemcutter.org/gems/active_cart}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Shopping Cart framework gem. Supports 'storage engines' and order total plugins}
  s.test_files = [
    "test/blueprints.rb",
     "test/fixtures/cart.rb",
     "test/fixtures/cart_item.rb",
     "test/fixtures/item.rb",
     "test/fixtures/order_total.rb",
     "test/mocks/test_cart_storage.rb",
     "test/mocks/test_item.rb",
     "test/mocks/test_order_total.rb",
     "test/performance/browsing_test.rb",
     "test/schema.rb",
     "test/test_helper.rb",
     "test/unit/acts_as_cart_test.rb",
     "test/unit/cart_storage_test.rb",
     "test/unit/cart_test.rb",
     "test/unit/item_test.rb",
     "test/unit/order_total_collection_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<aasm>, [">= 0"])
      s.add_development_dependency(%q<redgreen>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
      s.add_development_dependency(%q<machinist>, [">= 0"])
      s.add_development_dependency(%q<faker>, [">= 0"])
    else
      s.add_dependency(%q<aasm>, [">= 0"])
      s.add_dependency(%q<redgreen>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0"])
      s.add_dependency(%q<machinist>, [">= 0"])
      s.add_dependency(%q<faker>, [">= 0"])
    end
  else
    s.add_dependency(%q<aasm>, [">= 0"])
    s.add_dependency(%q<redgreen>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0"])
    s.add_dependency(%q<machinist>, [">= 0"])
    s.add_dependency(%q<faker>, [">= 0"])
  end
end

